language: node_js
node_js:
  - '10'
  - '12'
sudo: required
cache: yarn
addons:
  chrome: stable
services:
  - xvfb
notifications:
  email: false
env:
  - CI=true
before_script:
  - export DISPLAY=:99.0
before_install:
  - npm config set scripts-prepend-node-path true
  - npm i -g yarn
install:
  - yarn
script:
  - yarn build
