language: node_js
node_js:
  - '12'
os: linux
dist: xenial
notifications:
  email: false
cache: yarn
before_install:
  - npm config set scripts-prepend-node-path true
install:
  - yarn --frozen-lockfile
script:
  - yarn build
