language: node_js
node_js:
  - '10'
  - '12'
sudo: required
cache: yarn
addons:
  chrome: stable
dist: xenial
services:
  - xvfb
notifications:
  email: false
before_install:
  - npm config set scripts-prepend-node-path true
  - npm i -g yarn
install:
  - yarn
script:
  - yarn build
