language: node_js
node_js:
  - '10'
  - '12'
sudo: required
cache: yarn
addons:
  chrome: stable
dist: xenial
services:
  - xvfb
notifications:
  email: false
install:
  - yarn --frozen-lockfile
script:
  - yarn build
