language: node_js
node_js:
  - '10'
  - '12'
cache: yarn
addons:
  chrome: stable
notifications:
  email: false
env:
  - CI=true
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - npm config set scripts-prepend-node-path true
  - npm i -g yarn
install:
  - yarn
script:
  - yarn build
