language: node_js
node_js:
  - '10'
  - '12'
os: linux
dist: xenial
addons:
  chrome: stable
services:
  - xvfb
notifications:
  email: false
cache: yarn
before_install:
  - npm config set scripts-prepend-node-path true
install:
  - yarn --frozen-lockfile
script:
  - yarn build
after_script:
  - cat .chrome/chrome_debug.log
